-- Supabase Database Schema Migration
-- ===================================
-- Authority: Authoritative migration database script.
-- Targets: inquiries, quote_requests, rate_limits.
-- Policies: Strict RLS (anon/authenticated users blocked from direct inserts/updates).
-- Functions: increment_rate_limit (SECURITY DEFINER with safe search_path).

-- ── 1. Create inquiries table ────────────────────────────────
CREATE TABLE IF NOT EXISTS public.inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id UUID NOT NULL UNIQUE,
  request_fingerprint TEXT NOT NULL,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT NULL,
  company TEXT NULL,
  message TEXT NOT NULL,
  consent_captured BOOLEAN NOT NULL,
  client_identity TEXT NOT NULL, -- Pseudonymous HMAC identity
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Enable Row Level Security
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;

-- ── 2. Create quote_requests table ───────────────────────────
CREATE TABLE IF NOT EXISTS public.quote_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id UUID NOT NULL UNIQUE,
  request_fingerprint TEXT NOT NULL,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT NULL,
  company TEXT NULL,
  project_location TEXT NOT NULL,
  estimated_qty NUMERIC NOT NULL,
  qty_unit TEXT NOT NULL,
  required_by DATE NULL,
  message TEXT NULL,
  brick_variant TEXT NOT NULL,
  consent_captured BOOLEAN NOT NULL,
  client_identity TEXT NOT NULL, -- Pseudonymous HMAC identity
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Enable Row Level Security
ALTER TABLE public.quote_requests ENABLE ROW LEVEL SECURITY;

-- ── 3. Create rate_limits table ──────────────────────────────
CREATE TABLE IF NOT EXISTS public.rate_limits (
  key_name TEXT PRIMARY KEY,
  request_count INT NOT NULL DEFAULT 1,
  reset_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Enable Row Level Security
ALTER TABLE public.rate_limits ENABLE ROW LEVEL SECURITY;

-- ── 4. RLS POLICIES (Strict Lockout) ─────────────────────────
-- Deny all anonymous and authenticated users direct access to inquiries/quotes.
-- Direct DB calls from browser bypass server endpoints will fail.
-- Only the serverless functions connecting with service_role can perform mutations.

DROP POLICY IF EXISTS "Deny all public mutations on inquiries" ON public.inquiries;
CREATE POLICY "Deny all public mutations on inquiries" ON public.inquiries
  FOR ALL TO public USING (false) WITH CHECK (false);

DROP POLICY IF EXISTS "Deny all public mutations on quote_requests" ON public.quote_requests;
CREATE POLICY "Deny all public mutations on quote_requests" ON public.quote_requests
  FOR ALL TO public USING (false) WITH CHECK (false);

DROP POLICY IF EXISTS "Deny all public mutations on rate_limits" ON public.rate_limits;
CREATE POLICY "Deny all public mutations on rate_limits" ON public.rate_limits
  FOR ALL TO public USING (false) WITH CHECK (false);

-- ── 5. SECURITY DEFINER rate limiting RPC function ──────────
-- Runs under SECURITY DEFINER privilege (bypasses RLS) but enforces a strict
-- search_path to prevent path injection vulnerabilities.
CREATE OR REPLACE FUNCTION public.increment_rate_limit(
  key_name text,
  max_limit int,
  window_seconds int
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  current_count int;
  current_reset timestamptz;
  remaining_count int;
  seconds_left int;
  is_allowed boolean;
  now_time timestamptz;
BEGIN
  now_time := clock_timestamp();
  
  -- Upsert check: find existing rate limit row or insert fresh one
  INSERT INTO public.rate_limits (key_name, request_count, reset_at)
  VALUES (
    key_name,
    1,
    now_time + (window_seconds * interval '1 second')
  )
  ON CONFLICT (key_name) DO UPDATE
  SET
    -- If current window has expired, reset count to 1 and push reset time forward
    request_count = CASE
      WHEN clock_timestamp() > public.rate_limits.reset_at THEN 1
      ELSE public.rate_limits.request_count + 1
    END,
    reset_at = CASE
      WHEN clock_timestamp() > public.rate_limits.reset_at THEN now_time + (window_seconds * interval '1 second')
      ELSE public.rate_limits.reset_at
    END
  RETURNING public.rate_limits.request_count, public.rate_limits.reset_at
  INTO current_count, current_reset;

  seconds_left := ceil(extract(epoch from (current_reset - now_time)))::int;
  seconds_left := greatest(0, seconds_left);

  IF current_count <= max_limit THEN
    is_allowed := true;
    remaining_count := max_limit - current_count;
  ELSE
    is_allowed := false;
    remaining_count := 0;
  END IF;

  RETURN json_build_object(
    'allowed', is_allowed,
    'limit', max_limit,
    'remaining', remaining_count,
    'reset_seconds', seconds_left
  );
END;
$$;

-- Grant execution to service_role and postgres roles only. Keep anon/authenticated blocked.
REVOKE EXECUTE ON FUNCTION public.increment_rate_limit(text, int, int) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.increment_rate_limit(text, int, int) TO service_role;
GRANT EXECUTE ON FUNCTION public.increment_rate_limit(text, int, int) TO postgres;
